import React from 'react';
import Box from '@mui/material/Box';
import type { SxProps, Theme } from '@mui/material';

const iconMap: Record<string, string> = {
  // Finance & Money
  Wallet: 'account_balance_wallet',
  PiggyBank: 'savings',
  DollarSign: 'attach_money',
  CreditCard: 'credit_card',
  Banknote: 'payments',
  Coins: 'monetization_on',
  TrendingUp: 'trending_up',
  TrendingDown: 'trending_down',
  BarChart: 'bar_chart',
  BarChart2: 'stacked_bar_chart',
  PieChart: 'pie_chart',
  LineChart: 'show_chart',
  Receipt: 'receipt',
  Calculator: 'calculate',
  Percent: 'percent',
  CircleDollarSign: 'price_change',
  BadgeDollarSign: 'loyalty',

  // Work & Business
  Briefcase: 'work',
  Building: 'business',
  Building2: 'corporate_fare',
  Factory: 'factory',
  Landmark: 'account_balance',
  Store: 'store',
  ShoppingCart: 'shopping_cart',
  Package: 'inventory_2',
  Boxes: 'all_inbox',
  Archive: 'archive',
  FileText: 'description',
  ClipboardList: 'list_alt',

  // Food & Drink
  Utensils: 'restaurant',
  Coffee: 'coffee',
  Pizza: 'local_pizza',
  Beer: 'sports_bar',
  Wine: 'wine_bar',
  Milk: 'local_cafe',
  IceCream2: 'icecream',
  Cake: 'cake',
  Cookie: 'cookie',
  Apple: 'nutrition',
  Salad: 'local_dining',
  Soup: 'soup_kitchen',
  Sandwich: 'fastfood',
  Beef: 'set_meal',
  Fish: 'set_meal',
  Egg: 'egg',
  CupSoda: 'no_meals',
  Martini: 'dinner_dining',
  UtensilsCrossed: 'dinner_dining',
  ChefHat: 'restaurant',

  // Transport & Travel
  Car: 'directions_car',
  Bus: 'directions_bus',
  Bike: 'pedal_bike',
  Plane: 'flight',
  Train: 'train',
  Ship: 'directions_boat',
  Fuel: 'local_gas_station',
  ParkingCircle: 'local_parking',
  Navigation: 'navigation',
  Map: 'map',
  MapPin: 'location_on',
  Compass: 'explore',
  Globe: 'language',
  Anchor: 'anchor',
  Rocket: 'rocket_launch',
  Truck: 'local_shipping',
  Sailboat: 'sailing',
  Tractor: 'agriculture',

  // Shopping & Lifestyle
  ShoppingBag: 'shopping_bag',
  Gift: 'card_giftcard',
  Tag: 'label',
  Tags: 'sell',
  Ticket: 'confirmation_number',
  Gem: 'diamond',
  Crown: 'stars',
  Shirt: 'checkroom',
  Glasses: 'visibility',
  Watch: 'watch',
  Scissors: 'content_cut',
  Sparkles: 'auto_awesome',
  Star: 'star',
  Heart: 'favorite',
  Flower: 'local_florist',
  Flower2: 'local_florist',
  Palette: 'palette',
  Paintbrush: 'brush',

  // Electronics & Tech
  Smartphone: 'smartphone',
  Laptop: 'laptop_mac',
  Monitor: 'desktop_mac',
  Tv: 'tv',
  Tablet: 'tablet_mac',
  Camera: 'photo_camera',
  Headphones: 'headphones',
  Speaker: 'volume_up',
  Radio: 'radio',
  Wifi: 'wifi',
  Bluetooth: 'bluetooth',
  Battery: 'battery_full',
  Cable: 'cable',
  Cpu: 'memory',
  HardDrive: 'storage',
  Printer: 'print',
  Mouse: 'mouse',
  Keyboard: 'keyboard',
  Gamepad: 'videogame_asset',
  Joystick: 'sports_esports',

  // Home & Utilities
  Home: 'home',
  Bed: 'hotel',
  Sofa: 'weekend',
  Lamp: 'light',
  LampDesk: 'nightlight',
  Lightbulb: 'lightbulb',
  Zap: 'bolt',
  Plug: 'power',
  Thermometer: 'device_thermostat',
  Fan: 'air',
  AirVent: 'air',
  Droplet: 'water_drop',
  Droplets: 'water',
  Flame: 'whatshot',
  Snowflake: 'ac_unit',
  Wind: 'air',
  Hammer: 'hardware',
  Wrench: 'build',
  Key: 'key',
  Lock: 'lock',
  DoorOpen: 'door_front',
  Trash2: 'delete',
  Recycle: 'recycling',
  Leaf: 'nature',
  TreePine: 'park',
  Trees: 'forest',

  // Health & Wellness
  HeartPulse: 'monitor_heart',
  Stethoscope: 'health_and_safety',
  Pill: 'medication',
  Syringe: 'vaccines',
  Activity: 'monitor_heart',
  Dumbbell: 'fitness_center',
  PersonStanding: 'settings_accessibility',
  Footprints: 'directions_walk',
  Brain: 'psychology',
  Eye: 'visibility',
  Ear: 'hearing',
  Hand: 'pan_tool',
  CircleUser: 'account_circle',
  Smile: 'sentiment_satisfied',
  Frown: 'sentiment_dissatisfied',
  Sun: 'wb_sunny',
  Moon: 'dark_mode',
  CloudSun: 'wb_cloudy',
  Umbrella: 'beach_access',
  Shield: 'security',
  ShieldCheck: 'verified_user',

  // Education & Kids
  BookOpen: 'menu_book',
  Book: 'book',
  BookMarked: 'bookmark',
  Notebook: 'edit_note',
  GraduationCap: 'school',
  School: 'school',
  Pencil: 'edit',
  PenTool: 'draw',
  Highlighter: 'highlight',
  Eraser: 'straighten',
  Ruler: 'straighten',
  Backpack: 'backpack',
  Baby: 'child_friendly',
  ToyBrick: 'toys',
  Puzzle: 'extension',

  // Entertainment
  Music: 'music_note',
  Music2: 'music_note',
  Music3: 'library_music',
  Music4: 'audiotrack',
  Mic: 'mic',
  Mic2: 'mic_external_on',
  Video: 'videocam',
  Film: 'movie',
  Clapperboard: 'theaters',
  Popcorn: 'local_movies',
  Dice1: 'casino',
  Dice5: 'casino',
  Trophy: 'emoji_events',
  Medal: 'military_tech',

  // Nature & Outdoors
  Mountain: 'landscape',
  MountainSnow: 'filter_hdr',
  Waves: 'waves',
  Sunrise: 'wb_twilight',
  Sunset: 'wb_twilight',
  Cloud: 'cloud',
  CloudRain: 'thunderstorm',
  CloudSnow: 'ac_unit',
  Rainbow: 'auto_awesome',
  Bird: 'pets',
  Cat: 'pets',
  Dog: 'pets',
  Bug: 'bug_report',
  Rabbit: 'pets',
  Squirrel: 'pets',
  Tent: 'festival',
  Binoculars: 'search',
  Flashlight: 'bolt',

  // Religious & Spiritual
  Church: 'church',
  Cross: 'add',
  BookHeart: 'auto_stories',

  // Communication & Social
  Phone: 'phone',
  PhoneCall: 'phone_in_talk',
  Mail: 'mail',
  MessageCircle: 'chat',
  Send: 'send',
  Share: 'share',
  Users: 'group',
  UserPlus: 'person_add',
  UserCheck: 'how_to_reg',
  Handshake: 'handshake',
  PartyPopper: 'celebration',

  // UI Actions
  Plus: 'add',
  Minus: 'remove',
  X: 'close',
  Check: 'check',
  Edit: 'edit',
  Edit2: 'edit',
  Save: 'save',
  ArrowRight: 'arrow_forward',
  ArrowLeft: 'arrow_back',
  ArrowUp: 'arrow_upward',
  ArrowDown: 'arrow_downward',
  RefreshCw: 'refresh',
  Search: 'search',
  Filter: 'filter_list',
  Settings: 'settings',
  Menu: 'menu',
  MoreHorizontal: 'more_horiz',
  MoreVertical: 'more_vert',
  AlertCircle: 'error',
  AlertTriangle: 'warning',
  Info: 'info',
  HelpCircle: 'help',
  CheckCircle: 'check_circle',
  XCircle: 'cancel',
  Calendar: 'calendar_today',
  CalendarDays: 'calendar_month',
  LogOut: 'logout',
  Download: 'download',
  Image: 'image',
  Database: 'storage',
  Loader: 'hourglass_empty',
  Inbox: 'inbox',
};

interface IconDisplayProps {
  name: string;
  className?: string;
  size?: number;
  sx?: SxProps<Theme>;
}

const IconDisplay: React.FC<IconDisplayProps> = ({ name, className, size = 20, sx }) => {
  const symbolName = iconMap[name] ?? 'help_outline';

  return (
    <Box
      component="span"
      className={className}
      aria-hidden="true"
      sx={{
        fontFamily: '"Material Symbols Outlined"',
        fontWeight: 400,
        fontStyle: 'normal',
        fontSize: size,
        lineHeight: 1,
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        letterSpacing: 'normal',
        textTransform: 'none',
        whiteSpace: 'nowrap',
        wordWrap: 'normal',
        direction: 'ltr',
        WebkitFontSmoothing: 'antialiased',
        fontVariationSettings: '"FILL" 0, "wght" 400, "GRAD" 0, "opsz" 24',
        ...sx as object,
      }}
    >
      {symbolName}
    </Box>
  );
};

export default IconDisplay;
